"""Regression tests ensuring ODT exports do not inject LDR branding."""

from unittest.mock import MagicMock, patch

from local_deep_research.exporters.odt_exporter import ODTExporter


def test_odt_export_passes_unbranded_markdown_to_pandoc():
    exporter = ODTExporter()
    source = "# Report\n\nEvidence and conclusions."
    completed = MagicMock(stdout=b"PK-mock-odt")

    with (
        patch(
            "local_deep_research.exporters.odt_exporter.pypandoc.get_pandoc_path",
            return_value="pandoc",
        ),
        patch(
            "local_deep_research.exporters.odt_exporter.subprocess.run",
            return_value=completed,
        ) as run,
    ):
        exporter.export(source)

    exported_markdown = run.call_args.kwargs["input"].decode("utf-8")
    assert exported_markdown == source
    assert "Generated by" not in exported_markdown
    assert "Local Deep Research" not in exported_markdown
    assert "Open Source AI Research Assistant" not in exported_markdown
    assert "github.com/LearningCircuit/local-deep-research" not in exported_markdown


def test_odt_exporter_has_no_attribution_footer_helper():
    assert not hasattr(ODTExporter(), "_add_footer")
